@startuml uc1_login_c

rectangle ": User" as user 
rectangle ": LoginUI" as view
rectangle ": UserControl" as controller
rectangle ": User" as database

user --r- view : > 1: getUserData() \n 4: showResult() <
view --d- controller : > 2: submitUserData(userId,password)
controller --r- database : > 3: bool isUser(userId,password)

@enduml