@startuml uc1_1_Register_c
rectangle ": User" as user
rectangle ": RegisterView" as  register
rectangle ": UserControl" as control
rectangle ": User" as database

user --r-> register : > 1: setUserData(userId,name, career,password) \n 4: showResult() <
register --r-> control : > 2: setUserData(userId,name, career,password)
control --r-> database : > 3: createNewUser(userId, name, carreer, password) 

@enduml