@startuml uc2_show_announcement_c

rectangle ": User" as actor
rectangle ": NotificationUI" as view
rectangle ": NotificationControl" as control
rectangle ": Notification" as database

actor --r- view : > 1: searchNotification(id) \n 4: showResult() <
view --d- control : > 2: searchNotification(id)
control --r- database : > 3: searchNotification(id)

@enduml