@startuml uc2_2_add_calendar_c

rectangle ": User" as user
rectangle ": AddEventUI" as calendarView
rectangle ": CalendarControl" as controller2
rectangle ": Event " as database3

user --r-> calendarView : > 1: addNewEvent(idEvent) \n 4: showResult() <
calendarView --d-> controller2 : > 2: addNewEvent(idEvent)
controller2 --r-> database3 : \n 3: addNewEvent(idEvent) >

@enduml