@startuml uc2_2_show_calendar_c
rectangle ": User" as user
rectangle ": ShowCalendarUI" as showCalendarUI
rectangle ": CalendarControl" as controller
rectangle ": Calendar" as database2

user --r-> showCalendarUI : > 1: showCalendarUser(userId) \n 4: showResult() < 
showCalendarUI --d-> controller : > 2: showCalendarUser(userId)
controller --r-> database2 : > 3: showCalendarUser(userId)  

@enduml