@startuml uc3_create_event_c
rectangle ": User" as user 
rectangle ": CreateEventUI" as view
rectangle ": EventControl" as control
rectangle ": Event" as database

user --r- view : > 1: setDataEvent(date, location, hour) \n 5: showResult() <
view --d- control : > 2: setDataEvent(date, location, hour)
control --r- database : \n 3: setNewEvent(id) >

@enduml