@startuml uc3_create_event_c
rectangle ": Member" as user
rectangle ": IU Create event" as view
rectangle ": Create event control" as control
rectangle ": Database create event" as database

user --r- view : > 1: setDataEvent() \n 5: showResult() <
view --r- control : > 2: setDataEvent()
control --r- database : > 3: setDataEvent() \n 4: createNewEvent() >

@enduml