@startuml uc4_publish_research_c

rectangle ": Member" as user
rectangle ": IU publish new research" as interface
rectangle ": publish controller" as controller
rectangle ": database publish research" as database 

user --r- interface : > 1: setDatapublish() \n 5: showResult() <
interface --r- controller : > 2: setDatapublish()
controller --r- database : > 3: setDatapublish() \n 4: createNewpublish() >
@enduml