@startuml uc4_publish_research_c

rectangle ": User" as user
rectangle ": PublishNewResearchUI" as interface
rectangle ": ResearchControl" as controller
rectangle ": Research" as database 

user --r- interface : > 1: setDataResearch(title, topic, id) \n 5: showResult() <
interface --d- controller : > 2: setDataResearch(title, topic, id)
controller --r- database : 3: setNewResearch(title, topic, id) >
@enduml