@startuml uc5-Edit_Account-Colaboration
rectangle ": User" as user
rectangle ": EditUserUI" as interface
rectangle ": UserControl" as controller
rectangle ": User" as database 

user --r- interface : > 1: setUserData(userId, password) \n 5: showResult() <
interface --d- controller : > 2: setUserData(userId, password)
controller --r- database : > 3: setUserData(userId, password)
@enduml