@startuml uc1_Login
:Member: as actor
boundary "IU Login" as interface
boundary "IU Register" as interface2
control "login controller" as controller
control "register control" as control
entity "database login" as database
entity "database register" as database2

'connections
actor -r-- interface
interface -u-- interface2
interface -r-- controller
controller -r-- database
interface2 -r-- control
control -r-- database2

@enduml