@startuml uc1_Login
:User: as actor
boundary "LoginUI" as interface
control "UserControl" as controller
entity "User" as database

'connections
actor -r-- interface
interface -r-- controller
controller -r-- database

@enduml

