@startuml uc_1_1_Register
:User: as actor
boundary "RegisterView" as register
control "UserControl" as control
entity "User"

'connections

actor --r-> register
register --r-> control
control -r-> User

@enduml