@startuml uc2_Show_announcement
:User: as actor
boundary "NotificationUI" as view
control "NotificationControl" as control
entity "Notification" as database2

'Connection
actor -r-- view
view -r-- control
control -r-- database2
@enduml