@startuml uc2_2_add_calendar
:User: as actor
boundary "AddEventUI" as addEvent
control "EventControl" as addEventController
entity Event

'connections

actor --r-> addEvent
addEvent --r-> addEventController
addEventController --r-> Event
@enduml