@startuml uc2_2_show_calenda
:User: as actor
boundary "ShowCalendarUI" as showCalendarView
control "CalendarControl" as controller
entity Calendar

'connections

actor --r-> showCalendarView
showCalendarView --r-> controller
controller --r-> Calendar
@enduml