@startuml uc5-Edit_Account-Analysis
:User: as actor
boundary "EditUserUI" as interface
control "UserControl" as controller
entity "User" as database

'connections
actor -r-- interface
interface -r-- controller
controller -r-- database
@enduml