@startuml uc3_create_event
:User: as actor
boundary "EditEventUI" as view
control "EventControl" as control
entity "Event" as database

'connections

actor --r- view
view --r- control
control --r- database
@enduml