@startuml diagrama_clases
skinparam linetype ortho
hide empty methods
hide empty circle
skinparam nodesep 100
skinparam ranksep 45
'Clases principales
class Facultad_virtual
class Usuario {
-tema_de_interes: String
}
class Informacion
class Evento
class Calendario

class Notificacion
class Publicacion
class Actividad
'Clases que heredan de usuario
class Estudiante
class Profesor
class Personal_apoyo
class Administrador
'Clases que heredan de Informacion
class Investigacion
class Proyecto
'Clases que heredan de Evento
class Taller
class Seminario
'Clases que heredan de Actividad
class Actividad_deportiva
class Grupo_de_Estudio
'Herencia
Usuario <|-- Estudiante
Usuario <|-l- Profesor
Usuario <|- Personal_apoyo
Usuario <|-l Administrador
Publicacion <|-- Informacion
Publicacion <|-- Evento
Publicacion <|-- Actividad
Informacion <|-- Investigacion
Informacion <|-- Proyecto
Actividad <|-- Actividad_deportiva
Actividad <|-- Grupo_de_Estudio
Evento <|-- Taller
Evento <|-- Seminario

'Conexiones
Facultad_virtual *-d- Usuario
Facultad_virtual *-d- Calendario
Evento "0..*" -u-o Calendario
'Relaciones

Usuario -u- "0..*" Notificacion : Recibe
Publicacion "0..*" -u- Usuario : Comparte
Administrador -l- Publicacion : Modera
Estudiante -l- Evento : Publica
Estudiante -l- Actividad : Publica
Profesor -l- Informacion : Publica

'Conexiones invisibles para formato del diagrama
Publicacion -u[hidden]-- Usuario
Publicacion -u[hidden]-- Administrador
@enduml