@startuml diagramaClases
skinparam linetype ortho
hide empty methods
hide empty circle
skinparam nodesep 100
skinparam ranksep 45
'Clases principales
class Campus
class Miembro
class Informacion
class Evento
class Calendario
class Anuncio
class Actividad
class Club
class "Tema de Interes" as TdInt

'Clases que heredan de miembro

class Estudiante {
-carrera
}
class Profesor
class "Personal apoyo" as cp

'Clases que heredan de Informacion

class Investigacion
class Proyecto

'Clases que heredan de Evento

class Taller
class Seminario
class "Evento institucional" as cei

'Clases que heredan de Actividad

class "Actividad deportiva" as cap
class "Grupo de Estudio" as cge

'Herencia

Miembro <|-- Estudiante
Miembro <|-l- Profesor
Miembro <|- cp
Anuncio <|-- Informacion
Anuncio <|-- Evento
Anuncio <|-- Actividad
Anuncio <|-- Club
Informacion <|-- Investigacion
Informacion <|-- Proyecto
Actividad <|--- cap
Actividad <|--- cge
Evento <|-- Taller
Evento <|-- Seminario

Evento <|--- cei

'Conexiones

Campus o-d- Miembro
Campus <-d- Calendario : tiene
Evento "0..*" -u-o Calendario
Club -> Actividad : tiene
Miembro -> TdInt : posee

'Relaciones

Anuncio "0..*" -u- Miembro : Comparte
Estudiante -l- Evento : Publica
Estudiante -l- Actividad : Publica
Profesor -l- Informacion : Publica
'Conexiones invisibles para formato del diagrama

Anuncio -u[hidden]-- Miembro

'Composicion y Agregacion
Club *-- TdInt

@enduml