@startuml
skinparam linetype ortho
hide empty methods
hide empty circle
skinparam nodesep 100
skinparam ranksep 45
'Clases principales
class Facultad
class Tema_De_Interes
class persona 
persona o-d- Tema_De_Interes
class Informacion
class Evento
class Calendario
class Publicacion
class Actividad
class Club {
 -tema de interes: string
}
'Clases que heredan de persona
class Estudiante {
 -carrera
}
class Profesor
class "Personal apoyo" as cp
class Administrador
'Clases que heredan de Informacion
class Investigacion
class Proyecto
'Clases que heredan de Evento
class Taller
class Seminario
class "Evento institucional" as cei
'Clases que heredan de Actividad
class "Actividad deportiva" as cap
class "Grupo de Estudio" as cge
'Herencia
persona <|-- Estudiante
persona <|-l- Profesor
persona <|- cp
persona <|-l Administrador
Publicacion <|-- Informacion
Publicacion <|-- Evento
Publicacion <|-- Actividad
Publicacion <|-- Club
Informacion <|-- Investigacion
Informacion <|-- Proyecto
Actividad <|-- cap
Actividad <|-- cge
Evento <|-- Taller
Evento <|-- Seminario
Evento <|-- cei
'Conexiones
Facultad o-d- persona
Facultad -d-> Calendario : tiene
Evento "0..*" -u-o Calendario
Club -> Actividad : tiene
'Relaciones
Publicacion "0..*" -u- persona : Comparte
Estudiante -l- Evento : Publica
Estudiante -l- Actividad : Publica
Profesor -l- Informacion : Publica
'Conexiones invisibles para formato del diagrama
Publicacion -u[hidden]-- persona
@enduml